/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_apadmin_cameraphoto_Yuv420POperate */

#ifndef _Included_com_example_apadmin_cameraphoto_Yuv420POperate
#define _Included_com_example_apadmin_cameraphoto_Yuv420POperate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_apadmin_cameraphoto_Yuv420POperate
 * Method:    NV21toYUV420P
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_Yuv420POperate_NV21toYUV420P
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_example_apadmin_cameraphoto_Yuv420POperate
 * Method:    NV21ToNV12
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_Yuv420POperate_NV21ToNV12
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_example_apadmin_cameraphoto_Yuv420POperate
 * Method:    YUV420PClockRot90
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_Yuv420POperate_YUV420PClockRot90
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
