/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_apadmin_cameraphoto_YuvOperateJni */

#ifndef _Included_com_example_apadmin_cameraphoto_YuvOperateJni
#define _Included_com_example_apadmin_cameraphoto_YuvOperateJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    startYuvEngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_startYuvEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    Yv12ToI420
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_Yv12ToI420
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    I420ToYv12
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_I420ToYv12
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    Nv21ToI420
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_Nv21ToI420
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    I420ToNv21
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_I420ToNv21
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    Nv21ToYV12
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_Nv21ToYV12
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    YV12ToNv21
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_YV12ToNv21
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    Nv21ToNv12
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_Nv21ToNv12
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    Nv12ToNv21
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_Nv12ToNv21
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    cutCommonYuv
 * Signature: (JIII[BII[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_cutCommonYuv
  (JNIEnv *, jclass, jlong, jint, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    getSpecYuvBuffer
 * Signature: (JI[B[BIIII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_getSpecYuvBuffer
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    yuvAddWaterMark
 * Signature: (JIII[BII[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_yuvAddWaterMark
  (JNIEnv *, jclass, jlong, jint, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    Nv21ClockWiseRotate90
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_Nv21ClockWiseRotate90
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    Nv12ClockWiseRotate90
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_Nv12ClockWiseRotate90
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    Nv21ClockWiseRotate180
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_Nv21ClockWiseRotate180
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    Nv21ClockWiseRotate270
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_Nv21ClockWiseRotate270
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    I420ClockWiseRotate90
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_I420ClockWiseRotate90
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    Yv12ClockWiseRotate90
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_Yv12ClockWiseRotate90
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_example_apadmin_cameraphoto_YuvOperateJni
 * Method:    stopYuvEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_apadmin_cameraphoto_YuvOperateJni_stopYuvEngine
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
